const frTabs = [
  "New Franchise",
  "Preseason",
  "Regular Season",
  "Postseason",
  "Start Offseason",
  "Coaches &amp; Owner's Box",
  "Roster Management",
  "Re-Sign Players",
  "Free Agency",
  "Draft",
  "Complete Offseason",
];
const frSteps = {
  0: { tabNum: 0, text: "Create Franchise" },
  1: { tabNum: 0, text: "First Time Setup" },
  2: { tabNum: 1, text: "Start Preseason" },
  3: { tabNum: 2, text: "Prepare CPU teams" },
  4: { tabNum: 2, text: "Prepare Depth Charts" },
  5: { tabNum: 2, text: "Start Regular Season" },
  6: { tabNum: 3, text: "Complete Postseason" },
  7: { tabNum: 4, text: "New Franchise File" },
  8: { tabNum: 4, text: "Editor adjustments" },
  9: { tabNum: 5, text: "Coaches" },
  10: { tabNum: 5, text: "Owner's Box" },
  11: { tabNum: 6, text: "Draft Class" },
  12: { tabNum: 6, text: "Progress Through Offseason" },
  13: { tabNum: 7, text: "Complete Re-Sign Players" },
  14: { tabNum: 8, text: "Progress to Free Agency" },
  15: { tabNum: 9, text: "Team Control" },
  16: { tabNum: 9, text: "Sim Draft In Game" },
  17: { tabNum: 9, text: "Complete Draft In Editor" },
  18: { tabNum: 9, text: "Sign Draft Picks In Game" },
  19: { tabNum: 10, text: "Progress Through the Rest of the Offseason" },
  20: { tabNum: 10, text: "Import Traded Draft Picks" },
};
const frItems = {
  0: { stepNum: 0, platform: [0], text: "Create new franchise", note: 0 },
  1: { stepNum: 0, platform: [0], text: "Skip Training Camp", note: 0 },
  2: { stepNum: 0, platform: [0], text: "Save and exit franchise", note: 0 },
  3: {
    stepNum: 1,
    platform: [1],
    text: "Set franchise options and injury sliders",
    note: 0,
  },
  4: { stepNum: 1, platform: [1], text: "Set progression weeks", note: 0 },
  5: { stepNum: 1, platform: [1, 2], text: "Set AI sliders", note: 0 },
  6: { stepNum: 1, platform: [2], text: "Set penalty sliders", note: 0 },
  7: {
    stepNum: 2,
    platform: [0],
    text: "Set sim injury slider to 30",
    note: 0,
  },
  8: { stepNum: 2, platform: [0], text: "Play or sim preseason", note: 0 },
  9: { stepNum: 2, platform: [0], text: "Progress to regular season", note: 0 },
  10: { stepNum: 2, platform: [0], text: "Revert sim injury slider", note: 0 },
  11: { stepNum: 2, platform: [0], text: "Save and exit franchise", note: 0 },
  12: {
    stepNum: 3,
    platform: [1],
    text: "Apply coach slider adjustments",
    note: 0,
  },
  13: { stepNum: 3, platform: [1, 2], text: "User control all teams", note: 0 },
  14: {
    stepNum: 3,
    platform: [0, 1, 2],
    text: "Review head coaches and note teams changing to/from 3-4 defense",
    note: 0,
  },
  15: {
    stepNum: 3,
    platform: [0, 1, 2],
    text: "Optimize MLB/DT/DE positions for teams changing to/from 3-4",
    note: 0,
  },
  16: {
    stepNum: 4,
    platform: [0, 1, 2],
    text: "Auto-reorder depth chart for all CPU teams",
    note: 0,
  },
  17: {
    stepNum: 4,
    platform: [0, 1, 2],
    text:
      "Review each team for obvious depth chart issues and make manual adjustments",
    note: 0,
  },
  18: {
    stepNum: 5,
    platform: [0],
    text: "Play/sim through regular season",
    note: 0,
  },
  19: { stepNum: 5, platform: [0], text: "Advance to postseason", note: 0 },
  20: {
    stepNum: 6,
    platform: [0],
    text: "Play/sim through playoffs and Super Bowl",
    note: 0,
  },
  21: {
    stepNum: 6,
    platform: [0],
    text: "Play/sim Pro Bowl, DO NOT ADVANCE TO OFFSEASON",
    note: 0,
  },
  22: { stepNum: 6, platform: [0], text: "Save franchise", note: 0 },
  23: {
    stepNum: 6,
    platform: [0],
    text: "Save as new file and exit franchise",
    note: 0,
  },
  24: {
    stepNum: 7,
    platform: [0],
    text: "Open new franchise file and advance to offseason",
    note: 0,
  },
  25: { stepNum: 7, platform: [0], text: "Save and exit franchise", note: 0 },
  26: {
    stepNum: 8,
    platform: [1, 2],
    text: "Remove user control for CPU teams",
    note: 0,
  },
  27: {
    stepNum: 8,
    platform: [1],
    text: "Revert coach slider adjustments",
    note: 0,
  },
  28: { stepNum: 8, platform: [1], text: "Run Advanced AWR Boost", note: 0 },
  29: { stepNum: 9, platform: [0], text: "Sign coaches if necessary", note: 0 },
  30: {
    stepNum: 9,
    platform: [0],
    text: "Review all teams and note new head coaches",
    note: 0,
  },
  31: {
    stepNum: 10,
    platform: [0],
    text: "Set prices and stadium updates as needed",
    note: 0,
  },
  32: {
    stepNum: 10,
    platform: [0],
    text: "Progress to Player Retirement",
    note: 0,
  },
  33: { stepNum: 10, platform: [0], text: "Save and exit franchise", note: 0 },
  34: { stepNum: 11, platform: [1], text: "Import draft class", note: 0 },
  35: { stepNum: 11, platform: [1], text: "Apply Rookie Ratings Fix", note: 0 },
  36: { stepNum: 11, platform: [1], text: "Apply player body fix", note: 0 },
  37: { stepNum: 11, platform: [1], text: "Apply career stat fix", note: 0 },
  38: {
    stepNum: 12,
    platform: [0],
    text: "Progress through Retired Players",
    note: 0,
  },
  39: {
    stepNum: 12,
    platform: [0],
    text: "Progress through Roster Management",
    note: 0,
  },
  40: {
    stepNum: 12,
    platform: [0],
    text: "Progress through Restricted Free Agents",
    note: 0,
  },
  41: {
    stepNum: 12,
    platform: [0],
    text: "Advance to Re-Sign Players",
    note: 0,
  },
  42: {
    stepNum: 13,
    platform: [0],
    text: "Re-sign players as needed but DO NOT ADVANCE",
    note: 0,
  },
  43: { stepNum: 13, platform: [0], text: "Save and exit franchise", note: 0 },
  44: {
    stepNum: 13,
    platform: [1],
    text: "Apply AWR regression fix",
    note: '(do not select "revert all ratings" or "all AWR changes")',
  },
  45: {
    stepNum: 14,
    platform: [0],
    text: "Progress through Free Agency to 0 days left, DO NOT ADVANCE",
    note: 0,
  },
  46: { stepNum: 14, platform: [0], text: "Save and exit franchise", note: 0 },
  47: {
    stepNum: 15,
    platform: [1, 2],
    text: "User control all teams",
    note: 0,
  },
  48: {
    stepNum: 16,
    platform: [0],
    text: "Sim draft and advance to Sign Draft Picks",
    note: "(do not sign any draft picks)",
  },
  49: { stepNum: 16, platform: [0], text: "Save and exit franchise", note: 0 },
  50: {
    stepNum: 17,
    platform: [2],
    text: "Complete draft in Madden Amp",
    note: 0,
  },
  51: {
    stepNum: 17,
    platform: [1, 2],
    text: "Remove user control for CPU teams",
    note: 0,
  },
  52: {
    stepNum: 18,
    platform: [0],
    text: "Sign rookies to dummy contracts",
    note: 0,
  },
  53: { stepNum: 18, platform: [0], text: "Advance to Free Agency", note: 0 },
  54: { stepNum: 18, platform: [0], text: "Save and exit franchise", note: 0 },
  55: {
    stepNum: 18,
    platform: [1],
    text: "Apply rookie contract fix",
    note: 0,
  },
  56: {
    stepNum: 19,
    platform: [0],
    text: "Complete Free Agency and advance",
    note: 0,
  },
  57: {
    stepNum: 19,
    platform: [0],
    text: "Reorder depth charts and advance",
    note: 0,
  },
  58: {
    stepNum: 19,
    platform: [0],
    text: "Start new season and advance to training camp",
    note: 0,
  },
  59: { stepNum: 19, platform: [0], text: "Save and exit franchise", note: 0 },
  60: {
    stepNum: 20,
    platform: [2],
    text: "Move traded draft picks from file",
    note: "(choose file saved at the end of draft)",
  },
  61: { stepNum: 20, platform: [0], text: "Skip training camp", note: 0 },
  62: { stepNum: 20, platform: [0], text: "Save and exit franchise", note: 0 },
};
